server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:8080/postgres
    username: postgres
    password: 280914
  jpa:
    show-sql: true

application:
  currency_url: https://www.cbr-xml-daily.ru/latest.js




